raygun.settings:
  type: mapping
  label: Settings
  mapping:
    apikey:
      type: string
    async_sending:
      type: integer
    send_version:
      type: integer
    application_version:
      type: string
    send_email:
      type: integer
    exceptions:
      type: integer
    error_handling:
      type: integer
    send_username:
      type: integer
